ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "IntegrationConfig" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Tenant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrafficData" ENABLE ROW LEVEL SECURITY;
